### 엑셀파일로 저장

In [1]:
data = {
  'name' : ['김김','이씨','박둘','최자','정지우'],
  'grand' : ['하늘반','바다반','숲반','우미반','소라반'],
  'korSco' : [90,80,70,100,90],
  'engSco' : [70,80,80,70,90],
  'avg' : [80.0,80.0,75.0,85.0,90.0],
  'hobby' : ['독서','','','요가','축구'] 
}

data

{'name': ['김김', '이씨', '박둘', '최자', '정지우'],
 'grand': ['하늘반', '바다반', '숲반', '우미반', '소라반'],
 'korSco': [90, 80, 70, 100, 90],
 'engSco': [70, 80, 80, 70, 90],
 'avg': [80.0, 80.0, 75.0, 85.0, 90.0],
 'hobby': ['독서', '', '', '요가', '축구']}

In [4]:
import pandas

df = pandas.DataFrame(data)

df

  name grand  korSco  engSco   avg hobby
0   김김   하늘반      90      70  80.0    독서
1   이씨   바다반      80      80  80.0
2   박둘    숲반      70      80  75.0
3   최자   우미반     100      70  85.0    요가
4  정지우   소라반      90      90  90.0    축구

In [6]:
# 데이터프레임을 엑셀파일로 저장
# 저장되는 위치는 현재 파이썬을 연 파일안에 만들어 진다.
df.to_excel('test1.xlsx')

In [9]:
# 엑셀 파일을 불러오기

df_excel = pandas.read_excel('test1.xlsx')

df_excel

# 인덱스도 엑셀에 등록이 되어 있기때문에 unnamed로 컬럼으로 들고오게됨
# 판다스는 엑셀파일을 들고오면서 다시 인덱스를 만들어서 들어옴 
# 빈 문자열은 NaN오류로??

   Unnamed: 0 name grand  korSco  engSco  avg hobby
0           0   김김   하늘반      90      70   80    독서
1           1   이씨   바다반      80      80   80   NaN
2           2   박둘    숲반      70      80   75   NaN
3           3   최자   우미반     100      70   85    요가
4           4  정지우   소라반      90      90   90    축구

In [16]:
df = pandas.DataFrame(data)

# 엑셀 파일로 저장할 때 인덱스 제외하기(보통은 제외해서 저장함)
#
df.to_excel('test2.xlsx',index=False)

PermissionError: [Errno 13] Permission denied: 'test2.xlsx'

In [15]:

# 엑셀 파일 불러오기

df_test2 = pandas.read_excel('test2.xlsx')

df_test2

  name grand  korSco  engSco  avg hobby
0   김김   하늘반      90      70   80    독서
1   이씨   바다반      80      80   80   NaN
2   박둘    숲반      70      80   75   NaN
3   최자   우미반     100      70   85    요가
4  정지우   소라반      90      90   90    축구